@startuml Login Use Case Detail
hide empty description

[*] --> Login
    note on link #LightBlue;line:blue;
        **User requests:**
        * Login
    end note
    
state Login{
    state S1 as " "
    state S2 as " "
    state IF1 <<choice>>

    [*] --> S1
    
    S1 --> S2
        note on link
            **System requires:**
            * Token
        end note
     
    S2 --> IF1
        note on link #LightBlue;line:blue;
            **User provides:**
            * Token
        end note
        
    IF1 --> [*]
    IF1 --> S1 : [NotValidToken]
        note on link
            **System shows:**
            * Invalid token
        end note   
}
Login  --> DASHBOARD_OPENED
@enduml