@startuml Start Collab

package Models{
    card Session
    card State
    
    Session --> State
        note on link
            * Next()
        end note
}

package Services{
    card WindowService
    card SfcSimulatorService
    card WatchFolderService
    
    SfcSimulatorService --> WatchFolderService
        note on link
            * Start()
        end note
}

package ViewModels{
    card StartViewModel
    
    StartViewModel --> SfcSimulatorService
        note on link
           * Start()
        end note
        
    StartViewModel --> Session
        note on link
            * Next()
        end note
    StartViewModel --> WindowService
        note on link
            * ShowToast(toastMessage)
        end note
}

package Views {
    card StartView
    
    StartView --> StartViewModel
        note on link
            * Start() 
        end note
}
@enduml
