// <auto-generated />
using System;
using Hermes.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermes.Migrations
{
    [DbContext(typeof(HermesLocalContext))]
    [Migration("20250603035408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Hermes.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Hermes.Models.Heartbeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ActPackRem")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ActPackSeq")
                        .HasColumnType("INTEGER");

                    b.Property<float>("BakeCurrTemp")
                        .HasColumnType("REAL");

                    b.Property<uint>("BakeRemTime")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BakeStat")
                        .HasColumnType("INTEGER");

                    b.Property<float>("BakeTgtTemp")
                        .HasColumnType("REAL");

                    b.Property<uint>("BakeTgtTime")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CleanLiq")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CoverBoxIn")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CoverRemCnt")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DevReset")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("EnvBrdStat")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GasPress")
                        .HasColumnType("REAL");

                    b.Property<byte>("MotBrd1Stat")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MotBrd2Stat")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ScanTgt")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SealLiq")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SealMotFlow")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SealMotRst")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SensHumi")
                        .HasColumnType("REAL");

                    b.Property<float>("SensTemp")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("SlideActStat")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SlideBoxIn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SlideInInfo")
                        .IsRequired()
                        .HasMaxLength(188)
                        .HasColumnType("BLOB");

                    b.Property<byte>("SortMotFlow")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SortMotRst")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Suck1Press")
                        .HasColumnType("REAL");

                    b.Property<float>("Suck2Press")
                        .HasColumnType("REAL");

                    b.Property<byte>("SysActStat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("TEXT");

                    b.Property<byte>("WasteBoxIn")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("XyleneLiq")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Heartbeat", (string)null);
                });

            modelBuilder.Entity("Hermes.Models.Record", b =>
                {
                    b.Property<string>("RecordId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordId");

                    b.ToTable("Record", (string)null);
                });

            modelBuilder.Entity("Hermes.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PathologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte>("SealState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlideId")
                        .HasMaxLength(16)
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SortState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Slides", (string)null);
                });

            modelBuilder.Entity("Hermes.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Department")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Hermes.Models.Slide", b =>
                {
                    b.HasOne("Hermes.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
