//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Log-in to Pushi 的本地化字符串。
        /// </summary>
        public static string c_login_title {
            get {
                return ResourceManager.GetString("c_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title bar is hidden 的本地化字符串。
        /// </summary>
        public static string c_main_window_title_bar_hidden {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The title bar has been hiddden 的本地化字符串。
        /// </summary>
        public static string c_main_window_title_bar_hidden_msg {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_hidden_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title bar has been shown 的本地化字符串。
        /// </summary>
        public static string c_main_window_title_bar_visible_msg {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_visible_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title bar is visible 的本地化字符串。
        /// </summary>
        public static string c_main_window_title_bar_vissible {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_vissible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Makes the app fullscreen 的本地化字符串。
        /// </summary>
        public static string c_main_window_tooltip_fullscreen {
            get {
                return ResourceManager.GetString("c_main_window_tooltip_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to toggle top menu 的本地化字符串。
        /// </summary>
        public static string c_main_window_tooltip_toggle_top_menu {
            get {
                return ResourceManager.GetString("c_main_window_tooltip_toggle_top_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string c_settings_category_general {
            get {
                return ResourceManager.GetString("c_settings_category_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uut processor 的本地化字符串。
        /// </summary>
        public static string c_settings_category_uut_processor {
            get {
                return ResourceManager.GetString("c_settings_category_uut_processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When SFC response contains this text, it will be evaluated as ok 的本地化字符串。
        /// </summary>
        public static string c_settings_description_additional_ok_sfc_response {
            get {
                return ResourceManager.GetString("c_settings_description_additional_ok_sfc_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical locations comma separated 的本地化字符串。
        /// </summary>
        public static string c_settings_description_critical_locations {
            get {
                return ResourceManager.GetString("c_settings_description_critical_locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show stop window when a failure is detected in a component listed in the &quot;Critical Locations&quot; setting. 的本地化字符串。
        /// </summary>
        public static string c_settings_description_enable_critical_location_stop {
            get {
                return ResourceManager.GetString("c_settings_description_enable_critical_location_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show stop window when an error occurs in sfc or when a flow error is detected. 的本地化字符串。
        /// </summary>
        public static string c_settings_description_enable_machine_stop {
            get {
                return ResourceManager.GetString("c_settings_description_enable_machine_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show stop window when 3 consecutive same faults or 5 same faults in 1 hour or 10 different faults in 1 hour are detected.
        ///
        /// 的本地化字符串。
        /// </summary>
        public static string c_settings_description_enable_rule_three_five_ten {
            get {
                return ResourceManager.GetString("c_settings_description_enable_rule_three_five_ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language of interface 的本地化字符串。
        /// </summary>
        public static string c_settings_description_language {
            get {
                return ResourceManager.GetString("c_settings_description_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max sfc send retries when failure 的本地化字符串。
        /// </summary>
        public static string c_settings_description_max_retries {
            get {
                return ResourceManager.GetString("c_settings_description_max_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close success window when this time is over 的本地化字符串。
        /// </summary>
        public static string c_settings_description_success_window_timeout {
            get {
                return ResourceManager.GetString("c_settings_description_success_window_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General delay while waiting for actions to happen 的本地化字符串。
        /// </summary>
        public static string c_settings_description_wait_delay_ms {
            get {
                return ResourceManager.GetString("c_settings_description_wait_delay_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common 的本地化字符串。
        /// </summary>
        public static string c_settings_group_common {
            get {
                return ResourceManager.GetString("c_settings_group_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Features 的本地化字符串。
        /// </summary>
        public static string c_settings_group_features {
            get {
                return ResourceManager.GetString("c_settings_group_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paths 的本地化字符串。
        /// </summary>
        public static string c_settings_group_paths {
            get {
                return ResourceManager.GetString("c_settings_group_paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 的本地化字符串。
        /// </summary>
        public static string c_settings_group_station {
            get {
                return ResourceManager.GetString("c_settings_group_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string c_settings_group_time {
            get {
                return ResourceManager.GetString("c_settings_group_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional sfc ok response 的本地化字符串。
        /// </summary>
        public static string c_settings_header_additional_ok_sfc_response {
            get {
                return ResourceManager.GetString("c_settings_header_additional_ok_sfc_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autostart UUT Processor 的本地化字符串。
        /// </summary>
        public static string c_settings_header_autostart_uut_processor {
            get {
                return ResourceManager.GetString("c_settings_header_autostart_uut_processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Path 的本地化字符串。
        /// </summary>
        public static string c_settings_header_backup_path {
            get {
                return ResourceManager.GetString("c_settings_header_backup_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical locations 的本地化字符串。
        /// </summary>
        public static string c_settings_header_critical_locations {
            get {
                return ResourceManager.GetString("c_settings_header_critical_locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database server 的本地化字符串。
        /// </summary>
        public static string c_settings_header_database_server {
            get {
                return ResourceManager.GetString("c_settings_header_database_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical location stop 的本地化字符串。
        /// </summary>
        public static string c_settings_header_enable_critical_location_stop {
            get {
                return ResourceManager.GetString("c_settings_header_enable_critical_location_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Sfc error stop 的本地化字符串。
        /// </summary>
        public static string c_settings_header_enable_machine_stop {
            get {
                return ResourceManager.GetString("c_settings_header_enable_machine_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule three five ten stop 的本地化字符串。
        /// </summary>
        public static string c_settings_header_enable_rule_three_five_ten {
            get {
                return ResourceManager.GetString("c_settings_header_enable_rule_three_five_ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gkg tunnel com port 的本地化字符串。
        /// </summary>
        public static string c_settings_header_gkg_tunnel_com_port {
            get {
                return ResourceManager.GetString("c_settings_header_gkg_tunnel_com_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input file extension 的本地化字符串。
        /// </summary>
        public static string c_settings_header_input_file_ext {
            get {
                return ResourceManager.GetString("c_settings_header_input_file_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Path 的本地化字符串。
        /// </summary>
        public static string c_settings_header_input_path {
            get {
                return ResourceManager.GetString("c_settings_header_input_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string c_settings_header_language {
            get {
                return ResourceManager.GetString("c_settings_header_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line name 的本地化字符串。
        /// </summary>
        public static string c_settings_header_line_name {
            get {
                return ResourceManager.GetString("c_settings_header_line_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logfile type 的本地化字符串。
        /// </summary>
        public static string c_settings_header_logfile_type {
            get {
                return ResourceManager.GetString("c_settings_header_logfile_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine type 的本地化字符串。
        /// </summary>
        public static string c_settings_header_machine_type {
            get {
                return ResourceManager.GetString("c_settings_header_machine_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max retries 的本地化字符串。
        /// </summary>
        public static string c_settings_header_max_retries {
            get {
                return ResourceManager.GetString("c_settings_header_max_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanner com port 的本地化字符串。
        /// </summary>
        public static string c_settings_header_scanner_com_port {
            get {
                return ResourceManager.GetString("c_settings_header_scanner_com_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send unit to repair 的本地化字符串。
        /// </summary>
        public static string c_settings_header_send_repair_file {
            get {
                return ResourceManager.GetString("c_settings_header_send_repair_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sfc Path 的本地化字符串。
        /// </summary>
        public static string c_settings_header_sfc_path {
            get {
                return ResourceManager.GetString("c_settings_header_sfc_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sfc response extension 的本地化字符串。
        /// </summary>
        public static string c_settings_header_sfc_response_ext {
            get {
                return ResourceManager.GetString("c_settings_header_sfc_response_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sfc Timeout 的本地化字符串。
        /// </summary>
        public static string c_settings_header_sfc_timeout {
            get {
                return ResourceManager.GetString("c_settings_header_sfc_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 的本地化字符串。
        /// </summary>
        public static string c_settings_header_station {
            get {
                return ResourceManager.GetString("c_settings_header_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station Id 的本地化字符串。
        /// </summary>
        public static string c_settings_header_station_id {
            get {
                return ResourceManager.GetString("c_settings_header_station_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success window timeout 的本地化字符串。
        /// </summary>
        public static string c_settings_header_success_window_timeout {
            get {
                return ResourceManager.GetString("c_settings_header_success_window_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hermes update url 的本地化字符串。
        /// </summary>
        public static string c_settings_header_update_manager_url {
            get {
                return ResourceManager.GetString("c_settings_header_update_manager_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait delay (ms) 的本地化字符串。
        /// </summary>
        public static string c_settings_header_wait_delay_ms {
            get {
                return ResourceManager.GetString("c_settings_header_wait_delay_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create critical fail logfile 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_create_log_critical_fail {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_critical_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create fail logfile 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_create_log_fail {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create fail logfile with custom defect 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_create_log_fail_with_custom_defect {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_fail_with_custom_defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create pass logfile 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_create_log_pass {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create pass logfile with custom defect 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_create_log_pass_with_defect {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_pass_with_defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show pass view 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_show_pass {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show repair view 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_show_repair {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show repair view with message 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_show_repair_with_message {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_repair_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show stop machine view 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_show_stop_machine {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_stop_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show stop line view 的本地化字符串。
        /// </summary>
        public static string c_sfc_sim_show_top_line {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_top_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response mode 的本地化字符串。
        /// </summary>
        public static string c_sfc_simulator_response_mode {
            get {
                return ResourceManager.GetString("c_sfc_simulator_response_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock 的本地化字符串。
        /// </summary>
        public static string c_token_unlock_button {
            get {
                return ResourceManager.GetString("c_token_unlock_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token 的本地化字符串。
        /// </summary>
        public static string c_token_watermark {
            get {
                return ResourceManager.GetString("c_token_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        public static string enum_admin {
            get {
                return ResourceManager.GetString("enum_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        public static string enum_administrator {
            get {
                return ResourceManager.GetString("enum_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AOI 的本地化字符串。
        /// </summary>
        public static string enum_aoi {
            get {
                return ResourceManager.GetString("enum_aoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automation 的本地化字符串。
        /// </summary>
        public static string enum_automation {
            get {
                return ResourceManager.GetString("enum_automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blocked 的本地化字符串。
        /// </summary>
        public static string enum_blocked {
            get {
                return ResourceManager.GetString("enum_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment engineering 的本地化字符串。
        /// </summary>
        public static string enum_ee {
            get {
                return ResourceManager.GetString("enum_ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        public static string enum_empty {
            get {
                return ResourceManager.GetString("enum_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engineer 的本地化字符串。
        /// </summary>
        public static string enum_engineer {
            get {
                return ResourceManager.GetString("enum_engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engineer Leader 的本地化字符串。
        /// </summary>
        public static string enum_engineerleader {
            get {
                return ResourceManager.GetString("enum_engineerleader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string enum_exit {
            get {
                return ResourceManager.GetString("enum_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string enum_failed {
            get {
                return ResourceManager.GetString("enum_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free access 的本地化字符串。
        /// </summary>
        public static string enum_freeaccess {
            get {
                return ResourceManager.GetString("enum_freeaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        public static string enum_idle {
            get {
                return ResourceManager.GetString("enum_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In use 的本地化字符串。
        /// </summary>
        public static string enum_inuse {
            get {
                return ResourceManager.GetString("enum_inuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kitting 的本地化字符串。
        /// </summary>
        public static string enum_kitting {
            get {
                return ResourceManager.GetString("enum_kitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 1 的本地化字符串。
        /// </summary>
        public static string enum_level1 {
            get {
                return ResourceManager.GetString("enum_level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 2 的本地化字符串。
        /// </summary>
        public static string enum_level2 {
            get {
                return ResourceManager.GetString("enum_level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 3 的本地化字符串。
        /// </summary>
        public static string enum_level3 {
            get {
                return ResourceManager.GetString("enum_level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 4 的本地化字符串。
        /// </summary>
        public static string enum_level4 {
            get {
                return ResourceManager.GetString("enum_level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 5 的本地化字符串。
        /// </summary>
        public static string enum_level5 {
            get {
                return ResourceManager.GetString("enum_level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 6 的本地化字符串。
        /// </summary>
        public static string enum_level6 {
            get {
                return ResourceManager.GetString("enum_level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 7 的本地化字符串。
        /// </summary>
        public static string enum_level7 {
            get {
                return ResourceManager.GetString("enum_level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 8 的本地化字符串。
        /// </summary>
        public static string enum_level8 {
            get {
                return ResourceManager.GetString("enum_level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 9 的本地化字符串。
        /// </summary>
        public static string enum_level9 {
            get {
                return ResourceManager.GetString("enum_level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded 的本地化字符串。
        /// </summary>
        public static string enum_loaded {
            get {
                return ResourceManager.GetString("enum_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturing 的本地化字符串。
        /// </summary>
        public static string enum_mfg {
            get {
                return ResourceManager.GetString("enum_mfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not recognized 的本地化字符串。
        /// </summary>
        public static string enum_not_recognized {
            get {
                return ResourceManager.GetString("enum_not_recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not sorted 的本地化字符串。
        /// </summary>
        public static string enum_not_sorted {
            get {
                return ResourceManager.GetString("enum_not_sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not ran 的本地化字符串。
        /// </summary>
        public static string enum_notran {
            get {
                return ResourceManager.GetString("enum_notran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string enum_ok {
            get {
                return ResourceManager.GetString("enum_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string enum_open {
            get {
                return ResourceManager.GetString("enum_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open admin tools 的本地化字符串。
        /// </summary>
        public static string enum_openadmintools {
            get {
                return ResourceManager.GetString("enum_openadmintools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open bender 的本地化字符串。
        /// </summary>
        public static string enum_openbender {
            get {
                return ResourceManager.GetString("enum_openbender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open logs 的本地化字符串。
        /// </summary>
        public static string enum_openlogs {
            get {
                return ResourceManager.GetString("enum_openlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open settings config 的本地化字符串。
        /// </summary>
        public static string enum_opensettingsconfig {
            get {
                return ResourceManager.GetString("enum_opensettingsconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open sfc simulator 的本地化字符串。
        /// </summary>
        public static string enum_opensfcsimulator {
            get {
                return ResourceManager.GetString("enum_opensfcsimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open user admin 的本地化字符串。
        /// </summary>
        public static string enum_openuseradmin {
            get {
                return ResourceManager.GetString("enum_openuseradmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open uut processor 的本地化字符串。
        /// </summary>
        public static string enum_openuutprocessor {
            get {
                return ResourceManager.GetString("enum_openuutprocessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        public static string enum_operator {
            get {
                return ResourceManager.GetString("enum_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator leader 的本地化字符串。
        /// </summary>
        public static string enum_operatorleader {
            get {
                return ResourceManager.GetString("enum_operatorleader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passed 的本地化字符串。
        /// </summary>
        public static string enum_passed {
            get {
                return ResourceManager.GetString("enum_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process engineering 的本地化字符串。
        /// </summary>
        public static string enum_process {
            get {
                return ResourceManager.GetString("enum_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        public static string enum_processing {
            get {
                return ResourceManager.GetString("enum_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 的本地化字符串。
        /// </summary>
        public static string enum_qa {
            get {
                return ResourceManager.GetString("enum_qa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recognized 的本地化字符串。
        /// </summary>
        public static string enum_recognized {
            get {
                return ResourceManager.GetString("enum_recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore aoi stop 的本地化字符串。
        /// </summary>
        public static string enum_restoreaoistop {
            get {
                return ResourceManager.GetString("enum_restoreaoistop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore axi stop 的本地化字符串。
        /// </summary>
        public static string enum_restoreaxistop {
            get {
                return ResourceManager.GetString("enum_restoreaxistop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore labeling machine stop 的本地化字符串。
        /// </summary>
        public static string enum_restorelabelingmachinestop {
            get {
                return ResourceManager.GetString("enum_restorelabelingmachinestop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore screen printer stop 的本地化字符串。
        /// </summary>
        public static string enum_restorescreenprinterstop {
            get {
                return ResourceManager.GetString("enum_restorescreenprinterstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore spi stop 的本地化字符串。
        /// </summary>
        public static string enum_restorespistop {
            get {
                return ResourceManager.GetString("enum_restorespistop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scann error 的本地化字符串。
        /// </summary>
        public static string enum_scanerror {
            get {
                return ResourceManager.GetString("enum_scanerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanned 的本地化字符串。
        /// </summary>
        public static string enum_scanned {
            get {
                return ResourceManager.GetString("enum_scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide blocked 的本地化字符串。
        /// </summary>
        public static string enum_slide_blocked {
            get {
                return ResourceManager.GetString("enum_slide_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted 的本地化字符串。
        /// </summary>
        public static string enum_sorted {
            get {
                return ResourceManager.GetString("enum_sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        public static string enum_stopped {
            get {
                return ResourceManager.GetString("enum_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supervisor 的本地化字符串。
        /// </summary>
        public static string enum_supervisor {
            get {
                return ResourceManager.GetString("enum_supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technician 的本地化字符串。
        /// </summary>
        public static string enum_technician {
            get {
                return ResourceManager.GetString("enum_technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string enum_timeout {
            get {
                return ResourceManager.GetString("enum_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string enum_unknown {
            get {
                return ResourceManager.GetString("enum_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used 的本地化字符串。
        /// </summary>
        public static string enum_used {
            get {
                return ResourceManager.GetString("enum_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong station 的本地化字符串。
        /// </summary>
        public static string enum_wrongstation {
            get {
                return ResourceManager.GetString("enum_wrongstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t resend unit under test 的本地化字符串。
        /// </summary>
        public static string msg_can_not_resed_uut {
            get {
                return ResourceManager.GetString("msg_can_not_resed_uut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the work order 的本地化字符串。
        /// </summary>
        public static string msg_change_wo {
            get {
                return ResourceManager.GetString("msg_change_wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete package from Hermes 的本地化字符串。
        /// </summary>
        public static string msg_delete_package_from_hermes {
            get {
                return ResourceManager.GetString("msg_delete_package_from_hermes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while getting the information from the database 的本地化字符串。
        /// </summary>
        public static string msg_error_while_getting_info_from_db {
            get {
                return ResourceManager.GetString("msg_error_while_getting_info_from_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature permission successfully added 的本地化字符串。
        /// </summary>
        public static string msg_feature_permission_added {
            get {
                return ResourceManager.GetString("msg_feature_permission_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature permission successfully deleted 的本地化字符串。
        /// </summary>
        public static string msg_feature_permission_deleted {
            get {
                return ResourceManager.GetString("msg_feature_permission_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user belongs to a different department 的本地化字符串。
        /// </summary>
        public static string msg_invalid_department {
            get {
                return ResourceManager.GetString("msg_invalid_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid employee id, it must be only numbers 的本地化字符串。
        /// </summary>
        public static string msg_invalid_employee_id {
            get {
                return ResourceManager.GetString("msg_invalid_employee_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The token is invalid 的本地化字符串。
        /// </summary>
        public static string msg_invalid_token {
            get {
                return ResourceManager.GetString("msg_invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid user information 的本地化字符串。
        /// </summary>
        public static string msg_invalid_user_info {
            get {
                return ResourceManager.GetString("msg_invalid_user_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid user/password 的本地化字符串。
        /// </summary>
        public static string msg_invalid_user_password {
            get {
                return ResourceManager.GetString("msg_invalid_user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No updates available 的本地化字符串。
        /// </summary>
        public static string msg_no_updates_available {
            get {
                return ResourceManager.GetString("msg_no_updates_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No users found 的本地化字符串。
        /// </summary>
        public static string msg_no_users_found {
            get {
                return ResourceManager.GetString("msg_no_users_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package added to Hermes 的本地化字符串。
        /// </summary>
        public static string msg_package_added_to_hermes {
            get {
                return ResourceManager.GetString("msg_package_added_to_hermes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package not found 的本地化字符串。
        /// </summary>
        public static string msg_package_not_found {
            get {
                return ResourceManager.GetString("msg_package_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package removed 的本地化字符串。
        /// </summary>
        public static string msg_package_removed {
            get {
                return ResourceManager.GetString("msg_package_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package removed from &quot;loaded&quot; 的本地化字符串。
        /// </summary>
        public static string msg_package_removed_from_loaded {
            get {
                return ResourceManager.GetString("msg_package_removed_from_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove package from loadder 的本地化字符串。
        /// </summary>
        public static string msg_remove_package_load {
            get {
                return ResourceManager.GetString("msg_remove_package_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove this user? 的本地化字符串。
        /// </summary>
        public static string msg_remove_user {
            get {
                return ResourceManager.GetString("msg_remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan the package&apos;s 2D code 的本地化字符串。
        /// </summary>
        public static string msg_scan_2d_package {
            get {
                return ResourceManager.GetString("msg_scan_2d_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error scanning serial number 的本地化字符串。
        /// </summary>
        public static string msg_scan_error {
            get {
                return ResourceManager.GetString("msg_scan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan the vendor 的本地化字符串。
        /// </summary>
        public static string msg_scan_vendor {
            get {
                return ResourceManager.GetString("msg_scan_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please restart the application to apply the changes 的本地化字符串。
        /// </summary>
        public static string msg_settings_changed_needs_restart {
            get {
                return ResourceManager.GetString("msg_settings_changed_needs_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SFC server not responding, please contact IT department 的本地化字符串。
        /// </summary>
        public static string msg_sfc_timeout {
            get {
                return ResourceManager.GetString("msg_sfc_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SFC unknown error 的本地化字符串。
        /// </summary>
        public static string msg_sfc_unkown_error {
            get {
                return ResourceManager.GetString("msg_sfc_unkown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please clean the pcb and feed it back into the screen printer 的本地化字符串。
        /// </summary>
        public static string msg_spi_repair {
            get {
                return ResourceManager.GetString("msg_spi_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task successfully executed 的本地化字符串。
        /// </summary>
        public static string msg_success_task {
            get {
                return ResourceManager.GetString("msg_success_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update available 的本地化字符串。
        /// </summary>
        public static string msg_update_available {
            get {
                return ResourceManager.GetString("msg_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User added 的本地化字符串。
        /// </summary>
        public static string msg_user_added {
            get {
                return ResourceManager.GetString("msg_user_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User already exists 的本地化字符串。
        /// </summary>
        public static string msg_user_already_exists {
            get {
                return ResourceManager.GetString("msg_user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User deleted 的本地化字符串。
        /// </summary>
        public static string msg_user_deleted {
            get {
                return ResourceManager.GetString("msg_user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User not found 的本地化字符串。
        /// </summary>
        public static string msg_user_not_found {
            get {
                return ResourceManager.GetString("msg_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User updated 的本地化字符串。
        /// </summary>
        public static string msg_user_updated {
            get {
                return ResourceManager.GetString("msg_user_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User without permission to excecute the action. 的本地化字符串。
        /// </summary>
        public static string msg_user_without_permission {
            get {
                return ResourceManager.GetString("msg_user_without_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The users have been exported to a CSV file 的本地化字符串。
        /// </summary>
        public static string msg_users_exported_to_csv {
            get {
                return ResourceManager.GetString("msg_users_exported_to_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UUT Processor started 的本地化字符串。
        /// </summary>
        public static string msg_uut_processor_started {
            get {
                return ResourceManager.GetString("msg_uut_processor_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UUT Processor stopped 的本地化字符串。
        /// </summary>
        public static string msg_uut_processor_stopped {
            get {
                return ResourceManager.GetString("msg_uut_processor_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while trying to wait for dummy board 的本地化字符串。
        /// </summary>
        public static string msg_wait_for_dummy_error {
            get {
                return ResourceManager.GetString("msg_wait_for_dummy_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for dummy board 的本地化字符串。
        /// </summary>
        public static string msg_waiting_dummy_board {
            get {
                return ResourceManager.GetString("msg_waiting_dummy_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work order not found 的本地化字符串。
        /// </summary>
        public static string msg_work_order_not_found {
            get {
                return ResourceManager.GetString("msg_work_order_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The uut does not correspond to this station 的本地化字符串。
        /// </summary>
        public static string msg_wrong_station {
            get {
                return ResourceManager.GetString("msg_wrong_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string txt_about {
            get {
                return ResourceManager.GetString("txt_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string txt_account {
            get {
                return ResourceManager.GetString("txt_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string txt_actions {
            get {
                return ResourceManager.GetString("txt_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string txt_add {
            get {
                return ResourceManager.GetString("txt_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add package 的本地化字符串。
        /// </summary>
        public static string txt_add_package {
            get {
                return ResourceManager.GetString("txt_add_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add user 的本地化字符串。
        /// </summary>
        public static string txt_add_user {
            get {
                return ResourceManager.GetString("txt_add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amin tools 的本地化字符串。
        /// </summary>
        public static string txt_admin_tools {
            get {
                return ResourceManager.GetString("txt_admin_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string txt_all {
            get {
                return ResourceManager.GetString("txt_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string txt_cancel {
            get {
                return ResourceManager.GetString("txt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string txt_check_for_updates {
            get {
                return ResourceManager.GetString("txt_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Com port 的本地化字符串。
        /// </summary>
        public static string txt_com_port {
            get {
                return ResourceManager.GetString("txt_com_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        public static string txt_connect {
            get {
                return ResourceManager.GetString("txt_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        public static string txt_connected {
            get {
                return ResourceManager.GetString("txt_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created at 的本地化字符串。
        /// </summary>
        public static string txt_created_at {
            get {
                return ResourceManager.GetString("txt_created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark theme 的本地化字符串。
        /// </summary>
        public static string txt_dark_theme {
            get {
                return ResourceManager.GetString("txt_dark_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string txt_date {
            get {
                return ResourceManager.GetString("txt_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defect 的本地化字符串。
        /// </summary>
        public static string txt_defect {
            get {
                return ResourceManager.GetString("txt_defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string txt_delete {
            get {
                return ResourceManager.GetString("txt_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        public static string txt_department {
            get {
                return ResourceManager.GetString("txt_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string txt_disconnect {
            get {
                return ResourceManager.GetString("txt_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        public static string txt_disconnected {
            get {
                return ResourceManager.GetString("txt_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dummy board 的本地化字符串。
        /// </summary>
        public static string txt_dummy_board {
            get {
                return ResourceManager.GetString("txt_dummy_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string txt_edit {
            get {
                return ResourceManager.GetString("txt_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit user 的本地化字符串。
        /// </summary>
        public static string txt_edit_user {
            get {
                return ResourceManager.GetString("txt_edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Employee 的本地化字符串。
        /// </summary>
        public static string txt_employee {
            get {
                return ResourceManager.GetString("txt_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string txt_error {
            get {
                return ResourceManager.GetString("txt_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error code 的本地化字符串。
        /// </summary>
        public static string txt_error_code {
            get {
                return ResourceManager.GetString("txt_error_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error flag 的本地化字符串。
        /// </summary>
        public static string txt_error_flag {
            get {
                return ResourceManager.GetString("txt_error_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string txt_exit {
            get {
                return ResourceManager.GetString("txt_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export table to csv 的本地化字符串。
        /// </summary>
        public static string txt_export_table_to_csv {
            get {
                return ResourceManager.GetString("txt_export_table_to_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature Permissions 的本地化字符串。
        /// </summary>
        public static string txt_features_permissions {
            get {
                return ResourceManager.GetString("txt_features_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string txt_file {
            get {
                return ResourceManager.GetString("txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string txt_filter {
            get {
                return ResourceManager.GetString("txt_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        public static string txt_from {
            get {
                return ResourceManager.GetString("txt_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fullscreen 的本地化字符串。
        /// </summary>
        public static string txt_fullscreen {
            get {
                return ResourceManager.GetString("txt_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General settings 的本地化字符串。
        /// </summary>
        public static string txt_general_settings {
            get {
                return ResourceManager.GetString("txt_general_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hermes 的本地化字符串。
        /// </summary>
        public static string txt_hermes {
            get {
                return ResourceManager.GetString("txt_hermes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden 的本地化字符串。
        /// </summary>
        public static string txt_hidden {
            get {
                return ResourceManager.GetString("txt_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string txt_id {
            get {
                return ResourceManager.GetString("txt_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In use 的本地化字符串。
        /// </summary>
        public static string txt_in_use {
            get {
                return ResourceManager.GetString("txt_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string txt_info {
            get {
                return ResourceManager.GetString("txt_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input 的本地化字符串。
        /// </summary>
        public static string txt_input {
            get {
                return ResourceManager.GetString("txt_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input dummy board 的本地化字符串。
        /// </summary>
        public static string txt_input_dummy {
            get {
                return ResourceManager.GetString("txt_input_dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid token 的本地化字符串。
        /// </summary>
        public static string txt_invalid_token {
            get {
                return ResourceManager.GetString("txt_invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last refresh 的本地化字符串。
        /// </summary>
        public static string txt_last_refresh {
            get {
                return ResourceManager.GetString("txt_last_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Later 的本地化字符串。
        /// </summary>
        public static string txt_later {
            get {
                return ResourceManager.GetString("txt_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string txt_level {
            get {
                return ResourceManager.GetString("txt_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light theme 的本地化字符串。
        /// </summary>
        public static string txt_light_theme {
            get {
                return ResourceManager.GetString("txt_light_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded 的本地化字符串。
        /// </summary>
        public static string txt_loaded {
            get {
                return ResourceManager.GetString("txt_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string txt_loading {
            get {
                return ResourceManager.GetString("txt_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string txt_location {
            get {
                return ResourceManager.GetString("txt_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging in... 的本地化字符串。
        /// </summary>
        public static string txt_logging_in {
            get {
                return ResourceManager.GetString("txt_logging_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string txt_login {
            get {
                return ResourceManager.GetString("txt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string txt_logout {
            get {
                return ResourceManager.GetString("txt_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum level 的本地化字符串。
        /// </summary>
        public static string txt_minimum_level {
            get {
                return ResourceManager.GetString("txt_minimum_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string txt_name {
            get {
                return ResourceManager.GetString("txt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string txt_no {
            get {
                return ResourceManager.GetString("txt_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found 的本地化字符串。
        /// </summary>
        public static string txt_not_found {
            get {
                return ResourceManager.GetString("txt_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string txt_ok {
            get {
                return ResourceManager.GetString("txt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Pushi app 的本地化字符串。
        /// </summary>
        public static string txt_open_hermes_app {
            get {
                return ResourceManager.GetString("txt_open_hermes_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string txt_password {
            get {
                return ResourceManager.GetString("txt_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string txt_path {
            get {
                return ResourceManager.GetString("txt_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission 的本地化字符串。
        /// </summary>
        public static string txt_permission {
            get {
                return ResourceManager.GetString("txt_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PkgId 的本地化字符串。
        /// </summary>
        public static string txt_pkgid {
            get {
                return ResourceManager.GetString("txt_pkgid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string txt_refresh {
            get {
                return ResourceManager.GetString("txt_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove user 的本地化字符串。
        /// </summary>
        public static string txt_remove_user {
            get {
                return ResourceManager.GetString("txt_remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair 的本地化字符串。
        /// </summary>
        public static string txt_repair {
            get {
                return ResourceManager.GetString("txt_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend 的本地化字符串。
        /// </summary>
        public static string txt_resend {
            get {
                return ResourceManager.GetString("txt_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string txt_restart {
            get {
                return ResourceManager.GetString("txt_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        public static string txt_running {
            get {
                return ResourceManager.GetString("txt_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanned 的本地化字符串。
        /// </summary>
        public static string txt_scanned {
            get {
                return ResourceManager.GetString("txt_scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanner 的本地化字符串。
        /// </summary>
        public static string txt_scanner {
            get {
                return ResourceManager.GetString("txt_scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string txt_search {
            get {
                return ResourceManager.GetString("txt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search PackageId 的本地化字符串。
        /// </summary>
        public static string txt_search_pkgid {
            get {
                return ResourceManager.GetString("txt_search_pkgid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select work order 的本地化字符串。
        /// </summary>
        public static string txt_select_work_order {
            get {
                return ResourceManager.GetString("txt_select_work_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial number 的本地化字符串。
        /// </summary>
        public static string txt_serial_number {
            get {
                return ResourceManager.GetString("txt_serial_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string txt_settings {
            get {
                return ResourceManager.GetString("txt_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings changed 的本地化字符串。
        /// </summary>
        public static string txt_settings_changed {
            get {
                return ResourceManager.GetString("txt_settings_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SFC open 的本地化字符串。
        /// </summary>
        public static string txt_sfc_open {
            get {
                return ResourceManager.GetString("txt_sfc_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sfc response 的本地化字符串。
        /// </summary>
        public static string txt_sfc_response {
            get {
                return ResourceManager.GetString("txt_sfc_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sfc response content 的本地化字符串。
        /// </summary>
        public static string txt_sfc_response_content {
            get {
                return ResourceManager.GetString("txt_sfc_response_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sfc Simulator 的本地化字符串。
        /// </summary>
        public static string txt_sfc_simulator {
            get {
                return ResourceManager.GetString("txt_sfc_simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show password 的本地化字符串。
        /// </summary>
        public static string txt_show_password {
            get {
                return ResourceManager.GetString("txt_show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shown 的本地化字符串。
        /// </summary>
        public static string txt_shown {
            get {
                return ResourceManager.GetString("txt_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string txt_start {
            get {
                return ResourceManager.GetString("txt_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string txt_status {
            get {
                return ResourceManager.GetString("txt_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string txt_stop {
            get {
                return ResourceManager.GetString("txt_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        public static string txt_stopped {
            get {
                return ResourceManager.GetString("txt_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string txt_success {
            get {
                return ResourceManager.GetString("txt_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test status 的本地化字符串。
        /// </summary>
        public static string txt_test_status {
            get {
                return ResourceManager.GetString("txt_test_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title bar 的本地化字符串。
        /// </summary>
        public static string txt_title_bar {
            get {
                return ResourceManager.GetString("txt_title_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        public static string txt_to {
            get {
                return ResourceManager.GetString("txt_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token 的本地化字符串。
        /// </summary>
        public static string txt_token {
            get {
                return ResourceManager.GetString("txt_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        public static string txt_trigger {
            get {
                return ResourceManager.GetString("txt_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string txt_update {
            get {
                return ResourceManager.GetString("txt_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version available 的本地化字符串。
        /// </summary>
        public static string txt_update_available {
            get {
                return ResourceManager.GetString("txt_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update level 的本地化字符串。
        /// </summary>
        public static string txt_update_level {
            get {
                return ResourceManager.GetString("txt_update_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used 的本地化字符串。
        /// </summary>
        public static string txt_used {
            get {
                return ResourceManager.GetString("txt_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string txt_user {
            get {
                return ResourceManager.GetString("txt_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User management 的本地化字符串。
        /// </summary>
        public static string txt_user_management {
            get {
                return ResourceManager.GetString("txt_user_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UUT Processor 的本地化字符串。
        /// </summary>
        public static string txt_uut_processor {
            get {
                return ResourceManager.GetString("txt_uut_processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string txt_view {
            get {
                return ResourceManager.GetString("txt_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View level 的本地化字符串。
        /// </summary>
        public static string txt_view_level {
            get {
                return ResourceManager.GetString("txt_view_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        public static string txt_visible {
            get {
                return ResourceManager.GetString("txt_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string txt_warning {
            get {
                return ResourceManager.GetString("txt_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string txt_welcome {
            get {
                return ResourceManager.GetString("txt_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work order 的本地化字符串。
        /// </summary>
        public static string txt_work_order {
            get {
                return ResourceManager.GetString("txt_work_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string txt_yes {
            get {
                return ResourceManager.GetString("txt_yes", resourceCulture);
            }
        }
    }
}
