//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-in to Hermes.
        /// </summary>
        public static string c_login_title {
            get {
                return ResourceManager.GetString("c_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar is hidden.
        /// </summary>
        public static string c_main_window_title_bar_hidden {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title bar has been hiddden.
        /// </summary>
        public static string c_main_window_title_bar_hidden_msg {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_hidden_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar has been shown.
        /// </summary>
        public static string c_main_window_title_bar_visible_msg {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_visible_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar is visible.
        /// </summary>
        public static string c_main_window_title_bar_vissible {
            get {
                return ResourceManager.GetString("c_main_window_title_bar_vissible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the app fullscreen.
        /// </summary>
        public static string c_main_window_tooltip_fullscreen {
            get {
                return ResourceManager.GetString("c_main_window_tooltip_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle top menu.
        /// </summary>
        public static string c_main_window_tooltip_toggle_top_menu {
            get {
                return ResourceManager.GetString("c_main_window_tooltip_toggle_top_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string c_settings_category_general {
            get {
                return ResourceManager.GetString("c_settings_category_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uut processor.
        /// </summary>
        public static string c_settings_category_uut_processor {
            get {
                return ResourceManager.GetString("c_settings_category_uut_processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of interface.
        /// </summary>
        public static string c_settings_description_language {
            get {
                return ResourceManager.GetString("c_settings_description_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max sfc send retries when failure.
        /// </summary>
        public static string c_settings_description_max_retries {
            get {
                return ResourceManager.GetString("c_settings_description_max_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close success window when this time is over.
        /// </summary>
        public static string c_settings_description_success_window_timeout {
            get {
                return ResourceManager.GetString("c_settings_description_success_window_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General delay while waiting for actions to happen.
        /// </summary>
        public static string c_settings_description_wait_delay_ms {
            get {
                return ResourceManager.GetString("c_settings_description_wait_delay_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string c_settings_group_common {
            get {
                return ResourceManager.GetString("c_settings_group_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string c_settings_group_paths {
            get {
                return ResourceManager.GetString("c_settings_group_paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string c_settings_group_station {
            get {
                return ResourceManager.GetString("c_settings_group_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string c_settings_group_time {
            get {
                return ResourceManager.GetString("c_settings_group_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart UUT Processor.
        /// </summary>
        public static string c_settings_header_autostart_uut_processor {
            get {
                return ResourceManager.GetString("c_settings_header_autostart_uut_processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Path.
        /// </summary>
        public static string c_settings_header_backup_path {
            get {
                return ResourceManager.GetString("c_settings_header_backup_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file extension.
        /// </summary>
        public static string c_settings_header_input_file_ext {
            get {
                return ResourceManager.GetString("c_settings_header_input_file_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Path.
        /// </summary>
        public static string c_settings_header_input_path {
            get {
                return ResourceManager.GetString("c_settings_header_input_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string c_settings_header_language {
            get {
                return ResourceManager.GetString("c_settings_header_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line name.
        /// </summary>
        public static string c_settings_header_line_name {
            get {
                return ResourceManager.GetString("c_settings_header_line_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfile type.
        /// </summary>
        public static string c_settings_header_logfile_type {
            get {
                return ResourceManager.GetString("c_settings_header_logfile_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine type.
        /// </summary>
        public static string c_settings_header_machine_type {
            get {
                return ResourceManager.GetString("c_settings_header_machine_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retries.
        /// </summary>
        public static string c_settings_header_max_retries {
            get {
                return ResourceManager.GetString("c_settings_header_max_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send unit to repair.
        /// </summary>
        public static string c_settings_header_send_repair_file {
            get {
                return ResourceManager.GetString("c_settings_header_send_repair_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfc Path.
        /// </summary>
        public static string c_settings_header_sfc_path {
            get {
                return ResourceManager.GetString("c_settings_header_sfc_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfc response extension.
        /// </summary>
        public static string c_settings_header_sfc_response_ext {
            get {
                return ResourceManager.GetString("c_settings_header_sfc_response_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfc Timeout.
        /// </summary>
        public static string c_settings_header_sfc_timeout {
            get {
                return ResourceManager.GetString("c_settings_header_sfc_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string c_settings_header_station {
            get {
                return ResourceManager.GetString("c_settings_header_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success window timeout.
        /// </summary>
        public static string c_settings_header_success_window_timeout {
            get {
                return ResourceManager.GetString("c_settings_header_success_window_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait delay (ms).
        /// </summary>
        public static string c_settings_header_wait_delay_ms {
            get {
                return ResourceManager.GetString("c_settings_header_wait_delay_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create critical fail logfile.
        /// </summary>
        public static string c_sfc_sim_create_log_critical_fail {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_critical_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create fail logfile.
        /// </summary>
        public static string c_sfc_sim_create_log_fail {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create fail logfile with custom defect.
        /// </summary>
        public static string c_sfc_sim_create_log_fail_with_custom_defect {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_fail_with_custom_defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pass logfile.
        /// </summary>
        public static string c_sfc_sim_create_log_pass {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pass logfile with custom defect.
        /// </summary>
        public static string c_sfc_sim_create_log_pass_with_defect {
            get {
                return ResourceManager.GetString("c_sfc_sim_create_log_pass_with_defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pass view.
        /// </summary>
        public static string c_sfc_sim_show_pass {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show repair view.
        /// </summary>
        public static string c_sfc_sim_show_repair {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show repair view with message.
        /// </summary>
        public static string c_sfc_sim_show_repair_with_message {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_repair_with_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show stop machine view.
        /// </summary>
        public static string c_sfc_sim_show_stop_machine {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_stop_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show stop line view.
        /// </summary>
        public static string c_sfc_sim_show_top_line {
            get {
                return ResourceManager.GetString("c_sfc_sim_show_top_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response mode.
        /// </summary>
        public static string c_sfc_simulator_response_mode {
            get {
                return ResourceManager.GetString("c_sfc_simulator_response_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string c_token_unlock_button {
            get {
                return ResourceManager.GetString("c_token_unlock_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string c_token_watermark {
            get {
                return ResourceManager.GetString("c_token_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string enum_administrator {
            get {
                return ResourceManager.GetString("enum_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI.
        /// </summary>
        public static string enum_aoi {
            get {
                return ResourceManager.GetString("enum_aoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string enum_blocked {
            get {
                return ResourceManager.GetString("enum_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment engineering.
        /// </summary>
        public static string enum_ee {
            get {
                return ResourceManager.GetString("enum_ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string enum_idle {
            get {
                return ResourceManager.GetString("enum_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        public static string enum_inuse {
            get {
                return ResourceManager.GetString("enum_inuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        public static string enum_level1 {
            get {
                return ResourceManager.GetString("enum_level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        public static string enum_level2 {
            get {
                return ResourceManager.GetString("enum_level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        public static string enum_level3 {
            get {
                return ResourceManager.GetString("enum_level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        public static string enum_level4 {
            get {
                return ResourceManager.GetString("enum_level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 5.
        /// </summary>
        public static string enum_level5 {
            get {
                return ResourceManager.GetString("enum_level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 6.
        /// </summary>
        public static string enum_level6 {
            get {
                return ResourceManager.GetString("enum_level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 7.
        /// </summary>
        public static string enum_level7 {
            get {
                return ResourceManager.GetString("enum_level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 8.
        /// </summary>
        public static string enum_level8 {
            get {
                return ResourceManager.GetString("enum_level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 9.
        /// </summary>
        public static string enum_level9 {
            get {
                return ResourceManager.GetString("enum_level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string enum_loaded {
            get {
                return ResourceManager.GetString("enum_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string enum_mfg {
            get {
                return ResourceManager.GetString("enum_mfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string enum_ok {
            get {
                return ResourceManager.GetString("enum_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string enum_open {
            get {
                return ResourceManager.GetString("enum_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string enum_processing {
            get {
                return ResourceManager.GetString("enum_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string enum_qa {
            get {
                return ResourceManager.GetString("enum_qa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string enum_scanned {
            get {
                return ResourceManager.GetString("enum_scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string enum_stopped {
            get {
                return ResourceManager.GetString("enum_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string enum_timeout {
            get {
                return ResourceManager.GetString("enum_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string enum_unknown {
            get {
                return ResourceManager.GetString("enum_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string enum_used {
            get {
                return ResourceManager.GetString("enum_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong station.
        /// </summary>
        public static string enum_wrongstation {
            get {
                return ResourceManager.GetString("enum_wrongstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the work order.
        /// </summary>
        public static string msg_change_wo {
            get {
                return ResourceManager.GetString("msg_change_wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete package from Hermes.
        /// </summary>
        public static string msg_delete_package_from_hermes {
            get {
                return ResourceManager.GetString("msg_delete_package_from_hermes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid.
        /// </summary>
        public static string msg_invalid_token {
            get {
                return ResourceManager.GetString("msg_invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user/password.
        /// </summary>
        public static string msg_invalid_user_password {
            get {
                return ResourceManager.GetString("msg_invalid_user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        public static string msg_no_users_found {
            get {
                return ResourceManager.GetString("msg_no_users_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove package from loadder.
        /// </summary>
        public static string msg_remove_package_load {
            get {
                return ResourceManager.GetString("msg_remove_package_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user?.
        /// </summary>
        public static string msg_remove_user {
            get {
                return ResourceManager.GetString("msg_remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the package&apos;s 2D code.
        /// </summary>
        public static string msg_scan_2d_package {
            get {
                return ResourceManager.GetString("msg_scan_2d_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the vendor.
        /// </summary>
        public static string msg_scan_vendor {
            get {
                return ResourceManager.GetString("msg_scan_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please clean the pcb and feed it back into the screen printer.
        /// </summary>
        public static string msg_spi_repair {
            get {
                return ResourceManager.GetString("msg_spi_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added.
        /// </summary>
        public static string msg_user_added {
            get {
                return ResourceManager.GetString("msg_user_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string msg_user_already_exists {
            get {
                return ResourceManager.GetString("msg_user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted.
        /// </summary>
        public static string msg_user_deleted {
            get {
                return ResourceManager.GetString("msg_user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string msg_user_not_found {
            get {
                return ResourceManager.GetString("msg_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        public static string msg_user_updated {
            get {
                return ResourceManager.GetString("msg_user_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string txt_about {
            get {
                return ResourceManager.GetString("txt_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string txt_account {
            get {
                return ResourceManager.GetString("txt_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string txt_actions {
            get {
                return ResourceManager.GetString("txt_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add package.
        /// </summary>
        public static string txt_add_package {
            get {
                return ResourceManager.GetString("txt_add_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string txt_add_user {
            get {
                return ResourceManager.GetString("txt_add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string txt_all {
            get {
                return ResourceManager.GetString("txt_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string txt_dark_theme {
            get {
                return ResourceManager.GetString("txt_dark_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string txt_date {
            get {
                return ResourceManager.GetString("txt_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string txt_defect {
            get {
                return ResourceManager.GetString("txt_defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string txt_department {
            get {
                return ResourceManager.GetString("txt_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string txt_edit_user {
            get {
                return ResourceManager.GetString("txt_edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string txt_employee {
            get {
                return ResourceManager.GetString("txt_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string txt_error {
            get {
                return ResourceManager.GetString("txt_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        public static string txt_error_code {
            get {
                return ResourceManager.GetString("txt_error_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error flag.
        /// </summary>
        public static string txt_error_flag {
            get {
                return ResourceManager.GetString("txt_error_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string txt_exit {
            get {
                return ResourceManager.GetString("txt_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export table to csv.
        /// </summary>
        public static string txt_export_table_to_csv {
            get {
                return ResourceManager.GetString("txt_export_table_to_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string txt_file {
            get {
                return ResourceManager.GetString("txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string txt_filter {
            get {
                return ResourceManager.GetString("txt_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string txt_from {
            get {
                return ResourceManager.GetString("txt_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string txt_fullscreen {
            get {
                return ResourceManager.GetString("txt_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string txt_general_settings {
            get {
                return ResourceManager.GetString("txt_general_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermes.
        /// </summary>
        public static string txt_hermes {
            get {
                return ResourceManager.GetString("txt_hermes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string txt_hidden {
            get {
                return ResourceManager.GetString("txt_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string txt_id {
            get {
                return ResourceManager.GetString("txt_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        public static string txt_in_use {
            get {
                return ResourceManager.GetString("txt_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string txt_invalid_token {
            get {
                return ResourceManager.GetString("txt_invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last refresh.
        /// </summary>
        public static string txt_last_refresh {
            get {
                return ResourceManager.GetString("txt_last_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string txt_level {
            get {
                return ResourceManager.GetString("txt_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string txt_light_theme {
            get {
                return ResourceManager.GetString("txt_light_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string txt_loaded {
            get {
                return ResourceManager.GetString("txt_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string txt_loading {
            get {
                return ResourceManager.GetString("txt_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string txt_location {
            get {
                return ResourceManager.GetString("txt_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string txt_logging_in {
            get {
                return ResourceManager.GetString("txt_logging_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string txt_login {
            get {
                return ResourceManager.GetString("txt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string txt_logout {
            get {
                return ResourceManager.GetString("txt_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txt_name {
            get {
                return ResourceManager.GetString("txt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string txt_no {
            get {
                return ResourceManager.GetString("txt_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string txt_ok {
            get {
                return ResourceManager.GetString("txt_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txt_password {
            get {
                return ResourceManager.GetString("txt_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string txt_path {
            get {
                return ResourceManager.GetString("txt_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkgId.
        /// </summary>
        public static string txt_pkgid {
            get {
                return ResourceManager.GetString("txt_pkgid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        public static string txt_remove_user {
            get {
                return ResourceManager.GetString("txt_remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string txt_repair {
            get {
                return ResourceManager.GetString("txt_repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string txt_running {
            get {
                return ResourceManager.GetString("txt_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string txt_scanned {
            get {
                return ResourceManager.GetString("txt_scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txt_search {
            get {
                return ResourceManager.GetString("txt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search PackageId.
        /// </summary>
        public static string txt_search_pkgid {
            get {
                return ResourceManager.GetString("txt_search_pkgid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select work order.
        /// </summary>
        public static string txt_select_work_order {
            get {
                return ResourceManager.GetString("txt_select_work_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string txt_serial_number {
            get {
                return ResourceManager.GetString("txt_serial_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string txt_settings {
            get {
                return ResourceManager.GetString("txt_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFC open.
        /// </summary>
        public static string txt_sfc_open {
            get {
                return ResourceManager.GetString("txt_sfc_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfc Simulator.
        /// </summary>
        public static string txt_sfc_simulator {
            get {
                return ResourceManager.GetString("txt_sfc_simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string txt_show_password {
            get {
                return ResourceManager.GetString("txt_show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown.
        /// </summary>
        public static string txt_shown {
            get {
                return ResourceManager.GetString("txt_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string txt_start {
            get {
                return ResourceManager.GetString("txt_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string txt_status {
            get {
                return ResourceManager.GetString("txt_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string txt_stop {
            get {
                return ResourceManager.GetString("txt_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string txt_stopped {
            get {
                return ResourceManager.GetString("txt_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string txt_success {
            get {
                return ResourceManager.GetString("txt_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title bar.
        /// </summary>
        public static string txt_title_bar {
            get {
                return ResourceManager.GetString("txt_title_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string txt_to {
            get {
                return ResourceManager.GetString("txt_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string txt_token {
            get {
                return ResourceManager.GetString("txt_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update level.
        /// </summary>
        public static string txt_update_level {
            get {
                return ResourceManager.GetString("txt_update_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string txt_used {
            get {
                return ResourceManager.GetString("txt_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string txt_user {
            get {
                return ResourceManager.GetString("txt_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUT Processor.
        /// </summary>
        public static string txt_uut_processor {
            get {
                return ResourceManager.GetString("txt_uut_processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string txt_view {
            get {
                return ResourceManager.GetString("txt_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View level.
        /// </summary>
        public static string txt_view_level {
            get {
                return ResourceManager.GetString("txt_view_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string txt_visible {
            get {
                return ResourceManager.GetString("txt_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string txt_welcome {
            get {
                return ResourceManager.GetString("txt_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work order.
        /// </summary>
        public static string txt_work_order {
            get {
                return ResourceManager.GetString("txt_work_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string txt_yes {
            get {
                return ResourceManager.GetString("txt_yes", resourceCulture);
            }
        }
    }
}
